import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
export default function Home() {

  const [city, setCity] = React.useState('sofia');
  const [weather, setWeather] = React.useState([]);
  const [val, setVal] = React.useState();
  const [celsius, setCelsius] = React.useState(false);

  const data = () => {

    fetch(`https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=2ac597dfa6e78bc7452bebd703abecd6`)
      .then(response => response.json())
      .then(data => setWeather(data))

  }

  React.useEffect(() => {
    data();
  }, [city])

  function handleChange(e) {
    e.preventDefault();
    setCity(val)
  }

  function toCelsius(fahrenheit) {
    let num = String(fahrenheit - 273.15);
    return (num.slice(0, 4))
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        {weather.coord ?
          <div>
            <p>Location: {weather.name}</p>
            <p>Sky: {weather.weather[0].main}</p>
            <p>Description: {weather.weather[0].description}</p>
            <div>Current temperature: {celsius ? toCelsius(weather.main.temp) + ' celsius' : weather.main.temp + ' kalvins'}</div>
            <button onClick={() => setCelsius(!celsius)}>{!celsius ? 'To kalvins' : 'To fahrenheit'}</button>
            <br></br>


            <img src={`http://openweathermap.org/img/w/${weather.weather[0].icon}.png`} />
            <p>Lon: {weather.coord.lon}</p>
            <p>Lat:{weather.coord.lat}</p>
            <p>Feels like:  {celsius ? toCelsius(weather.main.feels_like) : weather.main.feels_like}</p>
            <p>Humidity:{weather.main.humidity}</p>
            <p>Wind speed:{weather.wind.speed} km/h</p>

            <form>
              <input type="text" onChange={() => setVal(event.target.value)} />
              <button onClick={handleChange}>Search</button>
            </form>
          </div>
          :

          <>
            <form>
              <input type="text" onChange={() => setVal(event.target.value)} />
              <button onClick={handleChange}>Submit</button>
            </form>
            {weather.cod && 'Location not found!'}</>
        }


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
